FIX: Fix missing std::set declaration
/run/build/BambuStudio/src/slic3r/GUI/Widgets/DropDown.cpp:281:10: error: ‘set’ is not a member of ‘std’
  281 |     std::set<wxString> groups;
      |          ^~~

(cherry picked from commit 842152b65a3584a9a59950f52260b20951dd09a5)