FIX: Fix missing wxStaticBitmap declaration
In file included from /run/build/BambuStudio/src/slic3r/GUI/DeviceErrorDialog.cpp:1:
/run/build/BambuStudio/src/slic3r/GUI/DeviceErrorDialog.hpp:78:5: error: ‘wxStaticBitmap’ does not name a type
   78 |     wxStaticBitmap* m_error_picture;
      |     ^~~~~~~~~~~~~~

(cherry picked from commit 834d2bc8026e38d7ed1d0bafa3e125baf412a322)