FIX: Fix missing boost::algorithm::split declaration
/run/build/BambuStudio/src/libslic3r/PrintConfig.cpp: In function ‘std::vector<std::map<int, int> > Slic3r::get_extruder_ams_count(const std::vector<std::__cxx11::basic_string<char> >&)’:
/run/build/BambuStudio/src/libslic3r/PrintConfig.cpp:454:27: error: ‘split’ is not a member of ‘boost::algorithm’
  454 |         boost::algorithm::split(ams_infos, str, boost::algorithm::is_any_of("|"));
      |                           ^~~~~

(cherry picked from commit bf32b5a489670df588ee2ac217275c6c0b8170ba)