FIX: Fix missing BOOST_LOG_TRIVIAL declaration
src/slic3r/GUI/DeviceCore/DevUtil.h:49:36: error: ‘BOOST_LOG_TRIVIAL’ was not declared in this scope
   49 |             BOOST_LOG_TRIVIAL(error) << __FUNCTION__ << ": " << e.what();
      |                                    ^

(cherry picked from commit 6c830d11e9066bc1afeb1f321f47e8e95931cb4a)